version: '3.7'

services:
    
    web:
        build:
            context: ./services/web 
            dockerfile: Dockerfile
        entrypoint: ['/usr/src/app/entrypoint.sh']
        volumes:
            - './services/web:/usr/src/app'
        ports:
            - 5001:5000
        environment: 
            - FLASK_ENV=development
            - APP_SETTINGS=application.config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:postgres@database:5432/drills_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@database:5432/drills_test
            - SECRET_KEY=supersecretkey
        depends_on:
            - database


    client:
        build:
            context: ./services/client
            dockerfile: Dockerfile
        volumes:
            - './services/client:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - 3007:3000
        environment:
            - NODE_ENV=development
            - REACT_APP_WEB_SERVICE_URL=${REACT_APP_WEB_SERVICE_URL}
        depends_on:
            - web

    database:
        build:
            context: ./services/web/application/db
            dockerfile: Dockerfile
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres